[build]
	command = "npm run build"
	functions = "functions"
	publish = "dist"
	environment = {AWS_LAMBDA_JS_RUNTIME = 'nodejs14.x', NODE_VERSION = '14'}

[dev]
	framework = "#custom"
	command = "npm run dev:webpack"
	targetPort = 8080
	port = 5000
	publish = "dist"
	autoLaunch = true